export const areas = [
    {
        name: 'block-1',
        block: 1,
        areaY: '10%',
        areaX: '0%',
        lots: [
            {
                name: 'John Doe',
                deceased: "Date: ",
                lotName: 'block-1-lot',
                lot: 1,
                areaY: '10%',
                areaX: '15%',
                size: '50px',
                occupied: true,
            },
            {
                name: 'Foe Bar',
                deceased: "Date: ",
                lotName: 'block-1-lot',
                lot: 2,
                areaY: '10%',
                areaX: '40%',
                size: '50px',
                occupied: true,
            },
            {
                name: 'Jane Doe',
                deceased: "Date: ",
                lotName: 'block-1-lot',
                lot: 3,
                areaY: '10%',
                areaX: '65%',
                size: '50px',
                occupied: true,
            },
            {
                name: 'Malcolm Function ',
                deceased: "Date: ",
                lotName: 'block-1-lot',
                lot: 4,
                areaY: '60%',
                areaX: '0%',
                size: '50px',
                occupied: true,
            },
            {
                name: 'Michael Doe',
                deceased: "Date: ",
                lotName: 'block-1-lot',
                lot: 5,
                areaY: '60%',
                areaX: '15%',
                size: '50px',
                occupied: true,
            },
            {
                name: 'Dominic L. Ement',
                deceased: "Date: ",
                lotName: 'block-1-lot',
                lot: 6,
                areaY: '60%',
                areaX: '40%',
                size: '50px',
                occupied: true,
            },
            {
                name: 'Dianne Ameter',
                deceased: "Date: ",
                lotName: 'block-1-lot',
                lot: 7,
                areaY: '60%',
                areaX: '65%',
                size: '50px',
                occupied: true,
            }
        ]
    }, 
    {
        name: 'block-2',
        block: 2,
        areaY: '30%',
        areaX: '0%',
        lots: [
            {
                name: 'Cecil Hipplington-Shoreditch',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 1,
                areaY: '5%',
                areaX: '0%',
                size: '50px',
                occupied: false,
            },
            {
                name: 'Valentino Morose',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 2,
                areaY: '5%',
                areaX: '18%',
                size: '50px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 3,
                areaY: '5%',
                areaX: '37%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 4,
                areaY: '17%',
                areaX: '37%',
                size: '25px',
                occupied: false,
            },
            {
                name: 'Elon Gated',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 5,
                areaY: '5%',
                areaX: '60%',
                size: '25px',
                occupied: true,
            },
            
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 6,
                areaY: '17%',
                areaX: '60%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 7,
                areaY: '5%',
                areaX: '80%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 8,
                areaY: '17%',
                areaX: '80%',
                size: '25px',
                occupied: false,
            },
            //second row
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 10,
                areaY: '33%',
                areaX: '0%',
                size: '50px',
                occupied: false,
            },
            {
                name: 'Bodrum Salvador',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 11,
                areaY: '33%',
                areaX: '20%',
                size: '50px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 12,
                areaY: '33%',
                areaX: '40%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 13,
                areaY: '45%',
                areaX: '40%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 14,
                areaY: '33%',
                areaX: '60%',
                size: '25px',
                occupied: false,
            },
            
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 15,
                areaY: '45%',
                areaX: '60%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 16,
                areaY: '33%',
                areaX: '80%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 17,
                areaY: '45%',
                areaX: '80%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 18,
                areaY: '58%',
                areaX: '0%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 19,
                areaY: '70%',
                areaX: '0%',
                size: '25px',
                occupied: false
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 20,
                areaY: '58%',
                areaX: '20%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 21,
                areaY: '70%',
                areaX: '20%',
                size: '25px',
                occupied: false
            },
            {
                name: "Dorothy Family",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 22,
                areaY: '58%',
                areaX: '40%',
                size: '50px',
                occupied: true,
            },
            {
                name: "Jackson Shoreditch",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 23,
                areaY: '58%',
                areaX: '64%',
                size: '50px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 24,
                areaY: '58%',
                areaX: '80%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 25,
                areaY: '70%',
                areaX: '80%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 26,
                areaY: '80%',
                areaX: '0%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 27,
                areaY: '90%',
                areaX: '0%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 28,
                areaY: '80%',
                areaX: '20%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 29,
                areaY: '90%',
                areaX: '20%',
                size: '25px',
                occupied: false,
            },
            {
                name: "John Smith",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 29,
                areaY: '80%',
                areaX: '40%',
                size: '50px',
                occupied: true,
            }, 
            {
                name: "John Taylor",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 30,
                areaY: '80%',
                areaX: '60%',
                size: '50px',
                occupied: true,
            },
            {
                name: "",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 30,
                areaY: '82%',
                areaX: '80%',
                size: '50px',
                occupied: false,
            },
        ]
    },
    {
        name: 'block-3',
        block: 3,
        areaY: '65%',
        areaX: '0%',
        lots: [
            {
                name: 'Humpty Dumpty',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 1,
                areaY: '5%',
                areaX: '0%',
                size: '50px',
                occupied: true,
            },
            {
                name: 'Dr. John Smith',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 2,
                areaY: '5%',
                areaX: '18%',
                size: '50px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 3,
                areaY: '1%',
                areaX: '37%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 4,
                areaY: '17%',
                areaX: '37%',
                size: '25px',
                occupied: false,
            },
            {
                name: 'Elon ',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 5,
                areaY: '5%',
                areaX: '60%',
                size: '50px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 6,
                areaY: '3%',
                areaX: '80%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 7,
                areaY: '18%',
                areaX: '80%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 8,
                areaY: '33%',
                areaX: '0%',
                size: '50px',
                occupied: false,
            },
            {
                name: 'Philip prophesy',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 9,
                areaY: '33%',
                areaX: '20%',
                size: '50px',
                occupied: true,
            },
            {
                name: 'Lily Queen',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 10,
                areaY: '30%',
                areaX: '40%',
                size: '25px',
                occupied: true,
            },
            {
                name: 'Ralph Johnson',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 11,
                areaY: '45%',
                areaX: '40%',
                size: '25px',
                occupied: false,
            },
            {
                name: "Jessica Jones",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 12,
                areaY: '33%',
                areaX: '60%',
                size: '50px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 13,
                areaY: '33%',
                areaX: '80%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 14,
                areaY: '45%',
                areaX: '80%',
                size: '25px',
                occupied: false,
            },
            {
                name: "Leslie Knope",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 15,
                areaY: '58%',
                areaX: '0%',
                size: '50px',
                occupied: true,
            },
            {
                name: "Kirsten Gillibrand",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 16,
                areaY: '58%',
                areaX: '20%',
                size: '50px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 17,
                areaY: '58%',
                areaX: '40%',
                size: '50px',
                occupied: false,
            },
            {
                name: "",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 18,
                areaY: '58%',
                areaX: '60%',
                size: '50px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 19,
                areaY: '58%',
                areaX: '80%',
                size: '25px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 20,
                areaY: '75%',
                areaX: '80%',
                size: '25px',
                occupied: false,
            },
        ] 
    },
    {
        name: 'block-4',
        block: 4,
        areaY: '10%',
        areaX: '32%',
        lots: [
            {
                name: 'Joey Tribbiani',
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 1,
                areaY: '0%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: 'Engr. John Smith',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 2,
                areaY: '10%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Paula Deen",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 3,
                areaY: '20%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 4,
                areaY: '30%',
                areaX: '0%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Jeslie Jones",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 5,
                areaY: '36%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Darren White",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 6,
                areaY: '46%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Jonesy Jones",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 7,
                areaY: '56%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Tesey Jones",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 8,
                areaY: '66%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: "",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 9,
                areaY: '77%',
                areaX: '0%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Darryl White",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 10,
                areaY: '87%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: 'Joey Tribbiani',
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 11,
                areaY: '0%',
                areaX: '5%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 12,
                areaY: '10%',
                areaX: '5%',
                size: '20px',
                occupied: true,
            },
            {
                name: "",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 13,
                areaY: '20%',
                areaX: '5%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Meredith Palmer",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 14,
                areaY: '30%',
                areaX: '5%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Quinn Dyer",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 15,
                areaY: '36%',
                areaX: '5%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Samantha Jones",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 16,
                areaY: '46%',
                areaX: '5%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Gwen Jones",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 17,
                areaY: '56%',
                areaX: '5%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Frank Jones",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 18,
                areaY: '66%',
                areaX: '5%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 19,
                areaY: '77%',
                areaX: '5%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 20,
                areaY: '87%',
                areaX: '5%',
                size: '20px',
                occupied: false,
            },
             {
                name: null,
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 21,
                areaY: '0%',
                areaX: '11%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 22,
                areaY: '10%',
                areaX: '11%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Chandler Bing",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 23,
                areaY: '20%',
                areaX: '11%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 24,
                areaY: '30%',
                areaX: '11%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 25,
                areaY: '36%',
                areaX: '11%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Monica Geller",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 26,
                areaY: '46%',
                areaX: '11%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Younge Geller",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 27,
                areaY: '56%',
                areaX: '11%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Jessica Geller",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 28,
                areaY: '66%',
                areaX: '11%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 29,
                areaY: '77%',
                areaX: '11%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Kramer Eric",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 30,
                areaY: '87%',
                areaX: '11%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 31,
                areaY: '0%',
                areaX: '17%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 32,
                areaY: '10%',
                areaX: '17%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 33,
                areaY: '20%',
                areaX: '17%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 34,
                areaY: '30%',
                areaX: '17%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 35,
                areaY: '36%',
                areaX: '17%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Darren Lynn",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 36,
                areaY: '46%',
                areaX: '17%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 37,
                areaY: '56%',
                areaX: '17%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Darryl Phil",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 38,
                areaY: '66%',
                areaX: '17%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 39,
                areaY: '77%',
                areaX: '17%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 40,
                areaY: '87%',
                areaX: '17%',
                size: '20px',
                occupied: null,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 41,
                areaY: '0%',
                areaX: '23%',
                size: '20px',
                occupied: null,
            },
            {
                name: "Kevin Geller",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 42,
                areaY: '10%',
                areaX: '23%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 43,
                areaY: '20%',
                areaX: '23%',
                size: '20px',
                occupied: null,
            },
            {
                name: "Barry Allen",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 44,
                areaY: '30%',
                areaX: '23%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 45,
                areaY: '40%',
                areaX: '23%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 46,
                areaY: '49%',
                areaX: '23%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 47,
                areaY: '59%',
                areaX: '23%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 48,
                areaY: '69%',
                areaX: '23%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 49,
                areaY: '78%',
                areaX: '23%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Quentin Beck",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 50,
                areaY: '86%',
                areaX: '23%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Maxwell Phillips",
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 51,
                areaY: '95%',
                areaX: '23%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 52,
                areaY: '0%',
                areaX: '30%',
                size: '20px',
                occupied: null,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 53,
                areaY: '10%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 54,
                areaY: '20%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 55,
                areaY: '30%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 56,
                areaY: '40%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 57,
                areaY: '50%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 58,
                areaY: '60%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 59,
                areaY: '70%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 60,
                areaY: '80%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
             {
                name: null,
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 61,
                areaY: '90%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: 'Jester',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 62,
                areaY: '0%',
                areaX: '36%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Khalid Shatranj",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 63,
                areaY: '10%',
                areaX: '36%',
                size: '20px',
                occupied: true,
            },
            {
                name: 'Henry Strano',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 64,
                areaY: '20%',
                areaX: '36%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 65,
                areaY: '33%',
                areaX: '36%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 66,
                areaY: '42%',
                areaX: '36%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 67,
                areaY: '50%',
                areaX: '36%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Jacky Depp",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 68,
                areaY: '58%',
                areaX: '36%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 69,
                areaY: '68%',
                areaX: '36%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Kramer Stone",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 70,
                areaY: '77%',
                areaX: '36%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 71,
                areaY: '88%',
                areaX: '36%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Jacker Poulin",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 72,
                areaY: '0%',
                areaX: '42%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 73,
                areaY: '10%',
                areaX: '42%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Karl Lagerfeld",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 74,
                areaY: '20%',
                areaX: '42%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Maxer Poulin",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 75,
                areaY: '30%',
                areaX: '42%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Hussein Al-Assad",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 76,
                areaY: '40%',
                areaX: '42%',
                size: '20px',
                occupied: true,
            },
            {
                name: 'Bobby Flay',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 77,
                areaY: '50%',
                areaX: '42%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Depp Star",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 78,
                areaY: '60%',
                areaX: '42%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Jason Statham",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 79,
                areaY: '70%',
                areaX: '42%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 80,
                areaY: '80%',
                areaX: '42%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Vincent Cassel",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 81,
                areaY: '90%',
                areaX: '42%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Kurt Cobain Jack",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 82,
                areaY: '50%',
                areaX: '50%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Kyle MacLachlan",
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 83,
                areaY: '60%',
                areaX: '50%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 84,
                areaY: '70%',
                areaX: '50%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 85,
                areaY: '80%',
                areaX: '50%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Jayson Licoln",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 86,
                areaY: '90%',
                areaX: '50%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 87,
                areaY: '50%',
                areaX: '57%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 88,
                areaY: '60%',
                areaX: '57%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 89,
                areaY: '70%',
                areaX: '57%',
                size: '20px',
                occupied: null,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 90,
                areaY: '80%',
                areaX: '57%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 91,
                areaY: '90%',
                areaX: '57%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Cole Mark",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 92,
                areaY: '0%',
                areaX: '62%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Anne-Marie",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 93,
                areaY: '0%',
                areaX: '62%',
                size: '20px',
                occupied: false,
            },
            {
                name: 'Bob Happy',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 94,
                areaY: '10%',
                areaX: '62%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Terry Gilliam",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 95,
                areaY: '20%',
                areaX: '62%',
                size: '20px',
                occupied: false,
            },
            {
                name: 'Henry Cavill',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 96,
                areaY: '30%',
                areaX: '62%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Teraer Gilliam",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 97,
                areaY: '45%',
                areaX: '62%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 98,
                areaY: '55%',
                areaX: '62%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 99,
                areaY: '65%',
                areaX: '62%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 100,
                areaY: '75%',
                areaX: '62%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 101,
                areaY: '85%',
                areaX: '62%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Kramer Stone",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 102,
                areaY: '95%',
                areaX: '62%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 103,
                areaY: '25%',
                areaX: '70%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 104,
                areaY: '35%',
                areaX: '70%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 105,
                areaY: '75%',
                areaX: '70%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Leonardo DiCaprio",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 106,
                areaY: '85%',
                areaX: '70%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Rosemary Clooney",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 107,
                areaY: '95%',
                areaX: '70%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Morgan Freeman",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 108,
                areaY: '5%',
                areaX: '80%',
                size: '50px',
                occupied: true,
            },
            {
                name: 'Jessica Alba',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 109,
                areaY: '30%',
                areaX: '80%',
                size: '50px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 110,
                areaY: '60%',
                areaX: '80%',
                size: '50px',
                occupied: false,
            },
            {
                name: "Jason Porter Mark",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 111,
                areaY: '80%',
                areaX: '80%',
                size: '50px',
                occupied: true,
            },
            {
                name: "Greenberg Wills",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 112,
                areaY: '0%',
                areaX: '86%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Desmond Howard",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 113,
                areaY: '10%',
                areaX: '86%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Ashley Judd",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 114,
                areaY: '20%',
                areaX: '86%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Kyle Mark",
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 115,
                areaY: '30%',
                areaX: '86%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 116,
                areaY: '40%',
                areaX: '86%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Freddy Krueger",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 117,
                areaY: '50%',
                areaX: '86%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 118,
                areaY: '60%',
                areaX: '86%',
                size: '100px',
                occupied: false,
            },
            {
                name: "Orlando Bloom",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 119,
                areaY: '0%',
                areaX: '93%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 120,
                areaY: '10%',
                areaX: '93%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Geary Garson",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 121,
                areaY: '20%',
                areaX: '93%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Hannibal Lecter",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 123,
                areaY: '30%',
                areaX: '93%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Tracy Morgan",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 124,
                areaY: '40%',
                areaX: '93%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 125,
                areaY: '50%',
                areaX: '93%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 126,
                areaY: '60%',
                areaX: '93%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Jayden Green",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 126,
                areaY: '70%',
                areaX: '93%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 127,
                areaY: '80%',
                areaX: '93%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Trevin Lane",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 128,
                areaY: '90%',
                areaX: '93%',
                size: '20px',
                occupied: true,
            },
        ] 
    },
    {
        name: 'block-5',
        block: 5,
        areaY: '47%',
        areaX: '32%',
        lots: [
            {
                name: 'Joey Tribbiani',
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 1,
                areaY: '0%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: 'Engr. John Smith',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 2,
                areaY: '10%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Paula Deen",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 3,
                areaY: '20%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 4,
                areaY: '30%',
                areaX: '0%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Jeslie Jones",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 5,
                areaY: '36%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Darren White",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 6,
                areaY: '46%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Jonesy Jones",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 7,
                areaY: '56%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Tesey Jones",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 8,
                areaY: '66%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: "",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 9,
                areaY: '77%',
                areaX: '0%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Darryl White",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 10,
                areaY: '87%',
                areaX: '0%',
                size: '20px',
                occupied: true,
            },
            {
                name: 'Joey Tribbiani',
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 11,
                areaY: '0%',
                areaX: '5%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 12,
                areaY: '10%',
                areaX: '5%',
                size: '20px',
                occupied: true,
            },
            {
                name: "",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 13,
                areaY: '20%',
                areaX: '5%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Meredith Palmer",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 14,
                areaY: '30%',
                areaX: '5%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Quinn Dyer",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 15,
                areaY: '36%',
                areaX: '5%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Samantha Jones",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 16,
                areaY: '46%',
                areaX: '5%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Gwen Jones",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 17,
                areaY: '56%',
                areaX: '5%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Frank Jones",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 18,
                areaY: '66%',
                areaX: '5%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 19,
                areaY: '77%',
                areaX: '5%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 20,
                areaY: '87%',
                areaX: '5%',
                size: '20px',
                occupied: false,
            },
             {
                name: null,
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 21,
                areaY: '0%',
                areaX: '11%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 22,
                areaY: '10%',
                areaX: '11%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Chandler Bing",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 23,
                areaY: '20%',
                areaX: '11%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 24,
                areaY: '30%',
                areaX: '11%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 25,
                areaY: '36%',
                areaX: '11%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Monica Geller",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 26,
                areaY: '46%',
                areaX: '11%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Younge Geller",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 27,
                areaY: '56%',
                areaX: '11%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Jessica Geller",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 28,
                areaY: '66%',
                areaX: '11%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 29,
                areaY: '77%',
                areaX: '11%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Kramer Eric",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 30,
                areaY: '87%',
                areaX: '11%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 31,
                areaY: '0%',
                areaX: '17%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 32,
                areaY: '10%',
                areaX: '17%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 33,
                areaY: '20%',
                areaX: '17%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 34,
                areaY: '30%',
                areaX: '17%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 35,
                areaY: '36%',
                areaX: '17%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Darren Lynn",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 36,
                areaY: '46%',
                areaX: '17%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 37,
                areaY: '56%',
                areaX: '17%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Darryl Phil",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 38,
                areaY: '66%',
                areaX: '17%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 39,
                areaY: '77%',
                areaX: '17%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 40,
                areaY: '87%',
                areaX: '17%',
                size: '20px',
                occupied: null,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 41,
                areaY: '0%',
                areaX: '23%',
                size: '20px',
                occupied: null,
            },
            {
                name: "Kevin Geller",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 42,
                areaY: '10%',
                areaX: '23%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 43,
                areaY: '20%',
                areaX: '23%',
                size: '20px',
                occupied: null,
            },
            {
                name: "Barry Allen",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 44,
                areaY: '30%',
                areaX: '23%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 45,
                areaY: '40%',
                areaX: '23%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 46,
                areaY: '49%',
                areaX: '23%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 47,
                areaY: '59%',
                areaX: '23%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 48,
                areaY: '69%',
                areaX: '23%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 49,
                areaY: '78%',
                areaX: '23%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Quentin Beck",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 50,
                areaY: '86%',
                areaX: '23%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Maxwell Phillips",
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 51,
                areaY: '95%',
                areaX: '23%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 52,
                areaY: '0%',
                areaX: '30%',
                size: '20px',
                occupied: null,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 53,
                areaY: '10%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 54,
                areaY: '20%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 55,
                areaY: '30%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 56,
                areaY: '40%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 57,
                areaY: '50%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 58,
                areaY: '60%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 59,
                areaY: '70%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 60,
                areaY: '80%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
             {
                name: null,
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 61,
                areaY: '90%',
                areaX: '30%',
                size: '20px',
                occupied: false,
            },
            {
                name: 'Jester',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 62,
                areaY: '0%',
                areaX: '36%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Khalid Shatranj",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 63,
                areaY: '10%',
                areaX: '36%',
                size: '20px',
                occupied: true,
            },
            {
                name: 'Henry Strano',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 64,
                areaY: '20%',
                areaX: '36%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 65,
                areaY: '33%',
                areaX: '36%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 66,
                areaY: '42%',
                areaX: '36%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 67,
                areaY: '50%',
                areaX: '36%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Jacky Depp",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 68,
                areaY: '58%',
                areaX: '36%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 69,
                areaY: '68%',
                areaX: '36%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Kramer Stone",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 70,
                areaY: '77%',
                areaX: '36%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 71,
                areaY: '88%',
                areaX: '36%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Jacker Poulin",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 72,
                areaY: '0%',
                areaX: '42%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 73,
                areaY: '10%',
                areaX: '42%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Karl Lagerfeld",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 74,
                areaY: '20%',
                areaX: '42%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Maxer Poulin",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 75,
                areaY: '30%',
                areaX: '42%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Hussein Al-Assad",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 76,
                areaY: '40%',
                areaX: '42%',
                size: '20px',
                occupied: true,
            },
            {
                name: 'Bobby Flay',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 77,
                areaY: '50%',
                areaX: '42%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Depp Star",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 78,
                areaY: '60%',
                areaX: '42%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Jason Statham",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 79,
                areaY: '70%',
                areaX: '42%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 80,
                areaY: '80%',
                areaX: '42%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Vincent Cassel",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 81,
                areaY: '90%',
                areaX: '42%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Kurt Cobain Jack",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 82,
                areaY: '50%',
                areaX: '50%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Kyle MacLachlan",
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 83,
                areaY: '60%',
                areaX: '50%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 84,
                areaY: '70%',
                areaX: '50%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 85,
                areaY: '80%',
                areaX: '50%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Jayson Licoln",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 86,
                areaY: '90%',
                areaX: '50%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 87,
                areaY: '50%',
                areaX: '57%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 88,
                areaY: '60%',
                areaX: '57%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 89,
                areaY: '70%',
                areaX: '57%',
                size: '20px',
                occupied: null,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 90,
                areaY: '80%',
                areaX: '57%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 91,
                areaY: '90%',
                areaX: '57%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Cole Mark",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 92,
                areaY: '0%',
                areaX: '62%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Anne-Marie",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 93,
                areaY: '0%',
                areaX: '62%',
                size: '20px',
                occupied: false,
            },
            {
                name: 'Bob Happy',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 94,
                areaY: '10%',
                areaX: '62%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Terry Gilliam",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 95,
                areaY: '20%',
                areaX: '62%',
                size: '20px',
                occupied: false,
            },
            {
                name: 'Henry Cavill',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 96,
                areaY: '30%',
                areaX: '62%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Teraer Gilliam",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 97,
                areaY: '45%',
                areaX: '62%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 98,
                areaY: '55%',
                areaX: '62%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 99,
                areaY: '65%',
                areaX: '62%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 100,
                areaY: '75%',
                areaX: '62%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 101,
                areaY: '85%',
                areaX: '62%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Kramer Stone",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 102,
                areaY: '95%',
                areaX: '62%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 103,
                areaY: '25%',
                areaX: '70%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 104,
                areaY: '35%',
                areaX: '70%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 105,
                areaY: '75%',
                areaX: '70%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Leonardo DiCaprio",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 106,
                areaY: '85%',
                areaX: '70%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Rosemary Clooney",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 107,
                areaY: '95%',
                areaX: '70%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Morgan Freeman",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 108,
                areaY: '5%',
                areaX: '80%',
                size: '50px',
                occupied: true,
            },
            {
                name: 'Jessica Alba',
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 109,
                areaY: '30%',
                areaX: '80%',
                size: '50px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 110,
                areaY: '60%',
                areaX: '80%',
                size: '50px',
                occupied: false,
            },
            {
                name: "Jason Porter Mark",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 111,
                areaY: '80%',
                areaX: '80%',
                size: '50px',
                occupied: true,
            },
            {
                name: "Greenberg Wills",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 112,
                areaY: '0%',
                areaX: '86%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Desmond Howard",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 113,
                areaY: '10%',
                areaX: '86%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Ashley Judd",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 114,
                areaY: '20%',
                areaX: '86%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Kyle Mark",
                deceased: "Date: ",
                lotName: 'block-4-lot',
                lot: 115,
                areaY: '30%',
                areaX: '86%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 116,
                areaY: '40%',
                areaX: '86%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Freddy Krueger",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 117,
                areaY: '50%',
                areaX: '86%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 118,
                areaY: '60%',
                areaX: '86%',
                size: '100px',
                occupied: false,
            },
            {
                name: "Orlando Bloom",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 119,
                areaY: '0%',
                areaX: '93%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 120,
                areaY: '10%',
                areaX: '93%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Geary Garson",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 121,
                areaY: '20%',
                areaX: '93%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Hannibal Lecter",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 123,
                areaY: '30%',
                areaX: '93%',
                size: '20px',
                occupied: true,
            },
            {
                name: "Tracy Morgan",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 124,
                areaY: '40%',
                areaX: '93%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 125,
                areaY: '50%',
                areaX: '93%',
                size: '20px',
                occupied: false,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 126,
                areaY: '60%',
                areaX: '93%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Jayden Green",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 126,
                areaY: '70%',
                areaX: '93%',
                size: '20px',
                occupied: true,
            },
            {
                name: null,
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 127,
                areaY: '80%',
                areaX: '93%',
                size: '20px',
                occupied: false,
            },
            {
                name: "Trevin Lane",
                deceased: "Date: ",
                lotName: 'block-2-lot',
                lot: 128,
                areaY: '90%',
                areaX: '93%',
                size: '20px',
                occupied: true,
            },
        ] 
    },

];
